services:
  - type: web
    name: lms-ui
    env: node
    plan: free
    buildCommand: |
      corepack enable
      corepack prepare pnpm@latest --activate
      pnpm install
      pnpm build
    startCommand: pnpm start
    runtime: node
    region: oregon
    rootDir: .
    buildFilter:
      paths:
        - package.json
        - pnpm-lock.yaml
        - render.yaml
    autoDeploy: true
